#!/bin/bash

dir_name=$1
num_files=$2
base_filename=$3

if (( $# == 3 )); then

	if ! test -d $dir_name; then

		mkdir $dir_name

	fi

	chmod u+rw $dir_name

	while (( $num_files < 1 || $num_files > 99 ))

		do

			echo "El segundo argumento no es válido, pues ha de ser un número comprendido entre 1 y 99."
			echo "Vuelva a introducir dicho dato."
			read num_files

		done

	for i in `seq 1 1 $num_files`
		
		do 
	
			if (( $i < 10 )); then
			
				touch ./$dir_name/$base_filename"0"$i

			else

				touch ./$dir_name/$base_filename$i

			fi
	
		done

	echo "El archivo se ha creado correctamente."


else

	echo "Se ha introducido un número incorrecto de parámetros."

fi



